surround subprocess.STARTUPINFO() with try-catch
On my computer (MacOS 10.10.5, python 2.7.10), subprocess module does not support STARTUPINFO. Adding try-catch prevents the code from crashing.

>>> import subprocess
>>> subprocess.STARTUPINFO()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'STARTUPINFO'
>>>